wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1679777272.518368
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 17
      - 23
      - 35
      4: 3.9.16
      5: 0.13.11
      8:
      - 1
      - 3
      - 8
